In [1]:
# header files
import numpy as np
import glob
import csv

In [3]:
image = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.reshape(image, (1, 9)))

[[1 2 3 4 5 6 7 8 9]]


In [5]:
print(-np.log((np.double(image)+1)/248))

[[4.82028157 4.41481646 4.12713439]
 [3.90399083 3.72166928 3.5675186 ]
 [3.4339872  3.31620417 3.21084365]]


In [ ]:
# function for normalizing image
def normalize_image(image):
    # OD threshold for transparent pixels
    beta = 0.15
    # tolerance for pseudo-min and pseudo-max
    alpha = 1
    # reference H&E OD matrix
    HERef = [[0.5626, 0.2159], [0.7201, 0.8012], [0.4062, 0.5581]]
    # reference maximum stain concentrations for H&E
    maxCRef = [[1.9705], [1.0308]]
    
    # get image dimensions
    height = image.shape[0]
    width = image.shape[1]
    
    # convert image to double type
    image = np.double(image)
    
    # resize image to (height*width, 3)
    image = np.reshape(image, (int(image.shape[0])*int(image.shape[1]), 3))
    
    # apply transmitted light intensity
    image_io = np.log((image+1) / 248)